CREATE TABLE `branches` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER UNSIGNED NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `is_headquarters` BOOLEAN NOT NULL DEFAULT false,
  `country_id` INTEGER UNSIGNED NOT NULL,
  `department_id` INTEGER UNSIGNED NOT NULL,
  `municipality_id` INTEGER UNSIGNED NOT NULL,
  `district_id` INTEGER UNSIGNED NOT NULL,
  `address_line` VARCHAR(500) NOT NULL,
  `phone` VARCHAR(30) NULL,
  `email` VARCHAR(191) NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `branches_company_code_key`(`company_id`, `code`),
  UNIQUE INDEX `branches_company_name_key`(`company_id`, `name`),
  UNIQUE INDEX `branches_id_company_key`(`id`, `company_id`),
  INDEX `branches_company_status_name_idx`(`company_id`, `status`, `name`),
  INDEX `branches_company_headquarters_idx`(`company_id`, `is_headquarters`),
  INDEX `branches_country_id_idx`(`country_id`),
  INDEX `branches_department_id_idx`(`department_id`),
  INDEX `branches_municipality_id_idx`(`municipality_id`),
  INDEX `branches_district_id_idx`(`district_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `branches_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `branches_country_id_fkey` FOREIGN KEY (`country_id`) REFERENCES `countries`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `branches_department_id_fkey` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `branches_municipality_id_fkey` FOREIGN KEY (`municipality_id`) REFERENCES `municipalities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `branches_district_id_fkey` FOREIGN KEY (`district_id`) REFERENCES `districts`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
