ALTER TABLE `expense_types`
  ADD COLUMN `landed_cost_category` ENUM('FREIGHT','INSURANCE','IMPORT_DUTY','OTHER','IMPORT_VAT') NOT NULL DEFAULT 'OTHER' AFTER `is_active`,
  ADD COLUMN `default_allocation_method` ENUM('FOB_VALUE','QUANTITY','WEIGHT','VOLUME','CIF_VALUE','EQUAL','MANUAL') NOT NULL DEFAULT 'FOB_VALUE' AFTER `landed_cost_category`,
  ADD COLUMN `is_capitalizable` BOOLEAN NOT NULL DEFAULT false AFTER `default_allocation_method`,
  ADD COLUMN `is_recoverable_tax` BOOLEAN NOT NULL DEFAULT false AFTER `is_capitalizable`,
  ADD COLUMN `is_cif_component` BOOLEAN NOT NULL DEFAULT false AFTER `is_recoverable_tax`;

CREATE TABLE `retaceos` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `company_id` INTEGER UNSIGNED NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `purchase_id` INTEGER UNSIGNED NOT NULL,
  `supplier_id` INTEGER UNSIGNED NOT NULL,
  `origin_country_id` INTEGER UNSIGNED NOT NULL,
  `created_by_user_id` INTEGER UNSIGNED NOT NULL,
  `retaceo_date` DATETIME(3) NOT NULL,
  `currency_code` CHAR(3) NOT NULL,
  `exchange_rate` DECIMAL(18,8) NOT NULL DEFAULT 1,
  `exchange_rate_date` DATE NULL,
  `import_invoice_number` VARCHAR(120) NULL,
  `import_invoice_date` DATE NULL,
  `import_policy_number` VARCHAR(120) NULL,
  `import_policy_date` DATE NULL,
  `calculation_version` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `total_fob` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `total_cif` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `total_capitalizable_costs` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `total_recoverable_taxes` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `total_landed_cost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `status` ENUM('DRAFT','CALCULATED','VERIFIED','CLOSED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `notes` TEXT NULL,
  `calculated_at` DATETIME(3) NULL,
  `calculated_by_user_id` INTEGER UNSIGNED NULL,
  `verified_at` DATETIME(3) NULL,
  `verified_by_user_id` INTEGER UNSIGNED NULL,
  `closed_at` DATETIME(3) NULL,
  `closed_by_user_id` INTEGER UNSIGNED NULL,
  `cancelled_at` DATETIME(3) NULL,
  `cancelled_by_user_id` INTEGER UNSIGNED NULL,
  `cancellation_reason` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `retaceos_uuid_key` (`uuid`),
  UNIQUE INDEX `retaceos_company_code_key` (`company_id`,`code`),
  UNIQUE INDEX `retaceos_company_purchase_key` (`purchase_id`,`company_id`),
  UNIQUE INDEX `retaceos_id_company_key` (`id`,`company_id`),
  INDEX `retaceos_company_status_date_idx` (`company_id`,`status`,`retaceo_date`),
  INDEX `retaceos_supplier_idx` (`company_id`,`supplier_id`),
  INDEX `retaceos_origin_country_idx` (`origin_country_id`),
  INDEX `retaceos_created_by_idx` (`created_by_user_id`),
  INDEX `retaceos_calculated_by_idx` (`calculated_by_user_id`),
  INDEX `retaceos_verified_by_idx` (`verified_by_user_id`),
  INDEX `retaceos_closed_by_idx` (`closed_by_user_id`),
  INDEX `retaceos_cancelled_by_idx` (`cancelled_by_user_id`),
  CONSTRAINT `retaceos_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_purchase_company_fkey` FOREIGN KEY (`purchase_id`,`company_id`) REFERENCES `purchases` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_supplier_company_fkey` FOREIGN KEY (`supplier_id`,`company_id`) REFERENCES `suppliers` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_origin_country_fkey` FOREIGN KEY (`origin_country_id`) REFERENCES `countries` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_created_by_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_calculated_by_fkey` FOREIGN KEY (`calculated_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_verified_by_fkey` FOREIGN KEY (`verified_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_closed_by_fkey` FOREIGN KEY (`closed_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceos_cancelled_by_fkey` FOREIGN KEY (`cancelled_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `retaceo_details` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER UNSIGNED NOT NULL,
  `retaceo_id` INTEGER UNSIGNED NOT NULL,
  `purchase_detail_id` INTEGER UNSIGNED NOT NULL,
  `product_id` INTEGER UNSIGNED NOT NULL,
  `product_unit_id` INTEGER UNSIGNED NOT NULL,
  `line_number` SMALLINT UNSIGNED NOT NULL,
  `quantity` DECIMAL(18,4) NOT NULL,
  `weight` DECIMAL(18,6) NULL,
  `volume` DECIMAL(18,6) NULL,
  `fob_unit_cost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `fob_total` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `allocated_capitalizable_cost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `total_cost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `retaceo_details_line_key` (`company_id`,`retaceo_id`,`line_number`),
  UNIQUE INDEX `retaceo_details_purchase_detail_key` (`company_id`,`retaceo_id`,`purchase_detail_id`),
  UNIQUE INDEX `retaceo_details_id_company_key` (`id`,`company_id`),
  INDEX `retaceo_details_product_idx` (`company_id`,`product_id`),
  INDEX `retaceo_details_unit_idx` (`company_id`,`product_unit_id`),
  CONSTRAINT `retaceo_details_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_details_retaceo_company_fkey` FOREIGN KEY (`retaceo_id`,`company_id`) REFERENCES `retaceos` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `retaceo_details_purchase_detail_company_fkey` FOREIGN KEY (`purchase_detail_id`,`company_id`) REFERENCES `purchase_details` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_details_product_company_fkey` FOREIGN KEY (`product_id`,`company_id`) REFERENCES `products` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_details_unit_company_fkey` FOREIGN KEY (`product_unit_id`,`company_id`) REFERENCES `product_units` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `retaceo_costs` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER UNSIGNED NOT NULL,
  `retaceo_id` INTEGER UNSIGNED NOT NULL,
  `expense_type_id` INTEGER UNSIGNED NOT NULL,
  `purchase_order_expense_id` INTEGER UNSIGNED NULL,
  `created_by_user_id` INTEGER UNSIGNED NOT NULL,
  `line_number` SMALLINT UNSIGNED NOT NULL,
  `description` VARCHAR(500) NULL,
  `document_number` VARCHAR(120) NULL,
  `document_date` DATE NULL,
  `currency_code` CHAR(3) NOT NULL,
  `original_amount` DECIMAL(18,6) NOT NULL,
  `exchange_rate` DECIMAL(18,8) NOT NULL DEFAULT 1,
  `exchange_rate_date` DATE NULL,
  `base_amount` DECIMAL(18,6) NOT NULL,
  `category` ENUM('FREIGHT','INSURANCE','IMPORT_DUTY','OTHER','IMPORT_VAT') NOT NULL DEFAULT 'OTHER',
  `is_capitalizable` BOOLEAN NOT NULL DEFAULT false,
  `is_recoverable_tax` BOOLEAN NOT NULL DEFAULT false,
  `is_cif_component` BOOLEAN NOT NULL DEFAULT false,
  `allocation_method` ENUM('FOB_VALUE','QUANTITY','WEIGHT','VOLUME','CIF_VALUE','EQUAL','MANUAL') NOT NULL DEFAULT 'FOB_VALUE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `retaceo_costs_line_key` (`company_id`,`retaceo_id`,`line_number`),
  UNIQUE INDEX `retaceo_costs_order_expense_key` (`company_id`,`retaceo_id`,`purchase_order_expense_id`),
  UNIQUE INDEX `retaceo_costs_id_company_key` (`id`,`company_id`),
  INDEX `retaceo_costs_expense_type_idx` (`company_id`,`expense_type_id`),
  INDEX `retaceo_costs_created_by_idx` (`created_by_user_id`),
  CONSTRAINT `retaceo_costs_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_costs_retaceo_company_fkey` FOREIGN KEY (`retaceo_id`,`company_id`) REFERENCES `retaceos` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `retaceo_costs_expense_type_company_fkey` FOREIGN KEY (`expense_type_id`,`company_id`) REFERENCES `expense_types` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_costs_order_expense_company_fkey` FOREIGN KEY (`purchase_order_expense_id`,`company_id`) REFERENCES `purchase_order_expenses` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_costs_created_by_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `retaceo_allocations` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER UNSIGNED NOT NULL,
  `retaceo_cost_id` INTEGER UNSIGNED NOT NULL,
  `retaceo_detail_id` INTEGER UNSIGNED NOT NULL,
  `allocation_method` ENUM('FOB_VALUE','QUANTITY','WEIGHT','VOLUME','CIF_VALUE','EQUAL','MANUAL') NOT NULL,
  `base_value` DECIMAL(24,8) NOT NULL,
  `total_base_value` DECIMAL(24,8) NOT NULL,
  `allocation_factor` DECIMAL(24,12) NOT NULL,
  `original_cost` DECIMAL(18,6) NOT NULL,
  `allocated_cost` DECIMAL(18,6) NOT NULL,
  `rounding_adjustment` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `retaceo_allocations_cost_detail_key` (`company_id`,`retaceo_cost_id`,`retaceo_detail_id`),
  INDEX `retaceo_allocations_detail_idx` (`company_id`,`retaceo_detail_id`),
  CONSTRAINT `retaceo_allocations_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `retaceo_allocations_cost_company_fkey` FOREIGN KEY (`retaceo_cost_id`,`company_id`) REFERENCES `retaceo_costs` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `retaceo_allocations_detail_company_fkey` FOREIGN KEY (`retaceo_detail_id`,`company_id`) REFERENCES `retaceo_details` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `permissions` (`code`,`resource`,`action`,`description`,`scope`,`created_at`) VALUES
('retaceos.read','retaceos','read','View landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.create','retaceos','create','Create landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.update','retaceos','update','Update draft landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.calculate','retaceos','calculate','Calculate landed costs.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.verify','retaceos','verify','Verify landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.close','retaceos','close','Close landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3)),
('retaceos.cancel','retaceos','cancel','Cancel landed-cost calculations.','COMPANY',CURRENT_TIMESTAMP(3));

INSERT IGNORE INTO `company_role_permissions` (`role_id`,`permission_id`,`company_id`)
SELECT `cr`.`id`,`p`.`id`,`cr`.`company_id`
FROM `company_roles` AS `cr`
JOIN `permissions` AS `p` ON `p`.`code` LIKE 'retaceos.%'
WHERE `cr`.`code` IN ('OWNER','ADMIN')
   OR (`cr`.`code` = 'OPERATOR' AND `p`.`code` IN ('retaceos.read','retaceos.create','retaceos.update','retaceos.calculate'))
   OR (`cr`.`code` = 'READ_ONLY' AND `p`.`code` = 'retaceos.read');
