import { Prisma } from '@prisma/client';
import { AppError } from '../../core/errors/app-error.js';
import { concurrencyConflict } from '../../core/errors/concurrency.js';
import { errorCodes } from '../../core/errors/error-codes.js';
import { businessCodeEntities,generateBusinessCode } from '../../core/code-generation/business-code.js';
import { paginationMeta } from '../../core/validation/pagination.js';
import { entityChangeOperations,entitySchemas,entityTypes } from '../entity-changes/entity-change.constants.js';
import { purchaseSnapshot } from '../entity-changes/entity-change.snapshots.js';
const d=(value)=>new Prisma.Decimal(value??0);const round=(value)=>value.toDecimalPlaces(6,Prisma.Decimal.ROUND_HALF_UP);
const invalid=(message,statusCode=400,details)=>new AppError({code:errorCodes.validation,message,statusCode,details});
const missing=()=>new AppError({code:errorCodes.notFound,message:'The requested purchase was not found.',statusCode:404});
const orderStatuses=['SENT','PARTIALLY_RECEIVED'];
export function createPurchasesService({repository,entityChangeService,runInTransaction,generateCode=generateBusinessCode}){
 const get=async(companyId,id,client)=>{const value=await repository.find(companyId,id,client);if(!value)throw missing();return value;};
 const record=(companyId,oldValue,newValue,context,operation,metadata,client)=>entityChangeService?.record({schemaName:entitySchemas.companies,entityType:entityTypes.purchase,entityId:newValue?.id??oldValue.id,companyId,operation,context,oldValues:purchaseSnapshot(oldValue),newValues:purchaseSnapshot(newValue),metadata},client);
 const loadOrder=async(companyId,orderId,client)=>{const order=await repository.findOrder(companyId,orderId,client);if(!order)throw invalid('The requested purchase order was not found.',404);if(!orderStatuses.includes(order.status))throw invalid('Only sent or partially received orders can receive merchandise.',409);if(!order.supplier.isActive||order.branch.status!=='ACTIVE'||!order.warehouse.isActive)throw invalid('The order supplier and destination must remain active.',409);return order;};
 const build=async(companyId,order,input,{excludePurchaseId,confirmedOnly=false}={},client)=>{const totals=await repository.receivedTotals(companyId,order.id,{excludePurchaseId,confirmedOnly},client);const byId=new Map(order.details.map(item=>[item.id,item]));let subtotal=d(0),discount=d(0),tax=d(0);const details=input.map((received,index)=>{const line=byId.get(received.purchaseOrderDetailId);if(!line)throw invalid('Every received line must belong to the selected purchase order.',400,{purchaseOrderDetailId:received.purchaseOrderDetailId});const quantity=d(received.quantityReceived),reserved=d(totals.get(line.id)),remaining=d(line.quantity).sub(reserved);if(quantity.greaterThan(remaining))throw invalid(`Line ${line.lineNumber} only has ${remaining.toString()} units available.`,409,{purchaseOrderDetailId:line.id,remainingQuantity:remaining.toString()});const gross=round(quantity.mul(line.unitPrice)),discountAmount=round(gross.mul(line.discountRate).div(100)),net=round(gross.sub(discountAmount)),taxAmount=round(net.mul(line.taxRate).div(100));subtotal=subtotal.add(gross);discount=discount.add(discountAmount);tax=tax.add(taxAmount);return{purchaseOrderDetailId:line.id,lineNumber:index+1,productId:line.productId,productUnitId:line.productUnitId,quantityOrdered:line.quantity,quantityReceived:quantity,unitPrice:line.unitPrice,grossAmount:gross,discountRate:line.discountRate,discountAmount,subtotal:net,taxRate:line.taxRate,taxAmount,total:round(net.add(taxAmount)),notes:received.notes??null};});return{details,subtotal:round(subtotal),discount:round(discount),tax:round(tax),total:round(subtotal.sub(discount).add(tax))};};
 const statusFromTotals=(order,totals)=>{const complete=order.details.every(line=>d(totals.get(line.id)).greaterThanOrEqualTo(line.quantity));if(complete)return'RECEIVED';const any=order.details.some(line=>d(totals.get(line.id)).greaterThan(0));return any?'PARTIALLY_RECEIVED':'SENT';};
 return{
  async list(companyId,query){const result=await repository.list(companyId,query);return{purchases:result.items,pagination:paginationMeta({...query,total:result.total})};},get,
  async availability(companyId,orderId,query={}){const order=await loadOrder(companyId,orderId);if(query.purchaseId){const purchase=await get(companyId,query.purchaseId);if(purchase.purchaseOrderId!==orderId||purchase.status!=='DRAFT')throw invalid('The purchase draft does not belong to the selected order.',409);}const totals=await repository.receivedTotals(companyId,orderId,{excludePurchaseId:query.purchaseId});return{purchaseOrder:{id:order.id,code:order.code,status:order.status,updatedAt:order.updatedAt,supplier:order.supplier,branch:order.branch,warehouse:order.warehouse,currencyCode:order.currencyCode},details:order.details.map(line=>{const reserved=d(totals.get(line.id));return{id:line.id,lineNumber:line.lineNumber,product:line.product,productUnit:line.productUnit,quantityOrdered:line.quantity,quantityReserved:reserved,quantityAvailable:d(line.quantity).sub(reserved)};}).filter(line=>d(line.quantityAvailable).greaterThan(0))};},
  async create(companyId,data,context){return runInTransaction(async(client)=>{const order=await loadOrder(companyId,data.purchaseOrderId,client);if(!await repository.claimOrder(companyId,order.id,new Date(data.expectedOrderUpdatedAt),orderStatuses,client))throw concurrencyConflict('purchase order',order.updatedAt);const calculated=await build(companyId,order,data.details,{},client);const created=await repository.create({companyId,code:await generateCode(client,businessCodeEntities.purchase,{companyId}),purchaseOrderId:order.id,supplierId:order.supplierId,branchId:order.branchId,warehouseId:order.warehouseId,receivedByUserId:context.actorUserId,purchaseDate:new Date(data.purchaseDate),supplierInvoiceNumber:data.supplierInvoiceNumber??null,supplierInvoiceDate:data.supplierInvoiceDate?new Date(data.supplierInvoiceDate):null,currencyCode:order.currencyCode,exchangeRate:order.exchangeRate,exchangeRateDate:order.exchangeRateDate,subtotal:calculated.subtotal,discount:calculated.discount,tax:calculated.tax,total:calculated.total,notes:data.notes??null,details:{create:calculated.details.map(item=>({companyId,...item}))}},client);await record(companyId,null,created,context,entityChangeOperations.create,{purchaseOrderId:order.id},client);return created;});},
  async update(companyId,id,data,context){const old=await get(companyId,id);if(old.status!=='DRAFT')throw invalid('Only draft purchases can be edited.',409);if(old.purchaseOrderId!==data.purchaseOrderId)throw invalid('The source purchase order cannot be changed.',409);return runInTransaction(async(client)=>{const order=await loadOrder(companyId,data.purchaseOrderId,client);if(!await repository.claimOrder(companyId,order.id,new Date(data.expectedOrderUpdatedAt),orderStatuses,client))throw concurrencyConflict('purchase order',order.updatedAt);const calculated=await build(companyId,order,data.details,{excludePurchaseId:id},client);const updated=await repository.replace(companyId,id,new Date(data.expectedUpdatedAt),{purchaseDate:new Date(data.purchaseDate),supplierInvoiceNumber:data.supplierInvoiceNumber??null,supplierInvoiceDate:data.supplierInvoiceDate?new Date(data.supplierInvoiceDate):null,subtotal:calculated.subtotal,discount:calculated.discount,tax:calculated.tax,total:calculated.total,notes:data.notes??null,details:calculated.details},client);if(!updated)throw concurrencyConflict('purchase',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,null,client);return updated;});},
  async receive(companyId,id,data,context){const old=await get(companyId,id);if(old.status!=='DRAFT')throw invalid('Only a draft purchase can be received.',409);if(!old.supplierInvoiceNumber||!old.supplierInvoiceDate)throw invalid('Supplier invoice number and date are required before confirming receipt.');return runInTransaction(async(client)=>{const order=await loadOrder(companyId,old.purchaseOrderId,client);if(!await repository.claimOrder(companyId,order.id,new Date(data.expectedOrderUpdatedAt),orderStatuses,client))throw concurrencyConflict('purchase order',order.updatedAt);await build(companyId,order,old.details.map(item=>({purchaseOrderDetailId:item.purchaseOrderDetailId,quantityReceived:item.quantityReceived})),{excludePurchaseId:id,confirmedOnly:true},client);const updated=await repository.transition(companyId,id,new Date(data.expectedUpdatedAt),['DRAFT'],{status:'RECEIVED',receivedAt:new Date()},client);if(!updated)throw concurrencyConflict('purchase',old.updatedAt);const confirmed=await repository.receivedTotals(companyId,order.id,{confirmedOnly:true},client),orderStatus=statusFromTotals(order,confirmed);await repository.updateOrderStatus(companyId,order.id,orderStatus,client);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'RECEIVE',purchaseOrderStatus:orderStatus},client);return updated;});},
  async verify(companyId,id,data,context){const old=await get(companyId,id);if(old.status!=='RECEIVED')throw invalid('Only a received purchase can be verified.',409);return runInTransaction(async(client)=>{const updated=await repository.transition(companyId,id,new Date(data.expectedUpdatedAt),['RECEIVED'],{status:'VERIFIED',verifiedAt:new Date(),verifiedByUserId:context.actorUserId},client);if(!updated)throw concurrencyConflict('purchase',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'VERIFY'},client);return updated;});},
  async close(companyId,id,data,context){const old=await get(companyId,id);if(old.status!=='VERIFIED')throw invalid('Only a verified purchase can be closed.',409);return runInTransaction(async(client)=>{const updated=await repository.transition(companyId,id,new Date(data.expectedUpdatedAt),['VERIFIED'],{status:'CLOSED',closedAt:new Date()},client);if(!updated)throw concurrencyConflict('purchase',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'CLOSE'},client);return updated;});},
  async cancel(companyId,id,data,context){const old=await get(companyId,id);if(old.status!=='DRAFT')throw invalid('Only a draft purchase can be cancelled.',409);return runInTransaction(async(client)=>{const order=await loadOrder(companyId,old.purchaseOrderId,client);if(!await repository.claimOrder(companyId,order.id,new Date(data.expectedOrderUpdatedAt),orderStatuses,client))throw concurrencyConflict('purchase order',order.updatedAt);const updated=await repository.transition(companyId,id,new Date(data.expectedUpdatedAt),['DRAFT'],{status:'CANCELLED',cancelledAt:new Date(),cancelledByUserId:context.actorUserId,cancellationReason:data.reason},client);if(!updated)throw concurrencyConflict('purchase',old.updatedAt);const confirmed=await repository.receivedTotals(companyId,order.id,{confirmedOnly:true},client),orderStatus=statusFromTotals(order,confirmed);await repository.updateOrderStatus(companyId,order.id,orderStatus,client);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'CANCEL',purchaseOrderStatus:orderStatus},client);return updated;});},
 };
}
