import { Router } from 'express';
import { authenticate } from '../../core/middleware/authenticate.js';
import { authorizeCompany } from '../../core/middleware/authorize.js';
import { validate } from '../../core/middleware/validate.js';
import { createPurchaseOrdersController } from './purchase-orders.controller.js';
import { createPurchaseOrderExpenseBody,deletePurchaseOrderExpenseBody,generatePurchaseOrdersBody,preparePurchaseOrderDocumentBody,purchaseOrderDocumentParams,purchaseOrderExpenseParams,purchaseOrderIdParams,purchaseOrderReasonTransitionBody,purchaseOrdersListQuery,purchaseOrderTransitionBody,registerPurchaseOrderDocumentBody,updatePurchaseOrderExpenseBody } from './purchase-orders.schemas.js';
export function createPurchaseOrdersRouter(service,auditService){const router=Router(),controller=createPurchaseOrdersController(service,auditService);router.use(authenticate);router.get('/',authorizeCompany('purchase_orders.read'),validate({query:purchaseOrdersListQuery}),controller.list);router.get('/:id',authorizeCompany('purchase_orders.read'),validate({params:purchaseOrderIdParams}),controller.get);router.post('/generate',authorizeCompany('purchase_orders.create'),validate({body:generatePurchaseOrdersBody}),controller.generate);for(const [path,permission,handler] of [['submit','purchase_orders.submit',controller.submit],['approve','purchase_orders.approve',controller.approve],['send','purchase_orders.send',controller.send]])router.post(`/:id/${path}`,authorizeCompany(permission),validate({params:purchaseOrderIdParams,body:purchaseOrderTransitionBody}),handler);router.post('/:id/cancel',authorizeCompany('purchase_orders.cancel'),validate({params:purchaseOrderIdParams,body:purchaseOrderReasonTransitionBody}),controller.cancel);
router.post('/:id/expenses',authorizeCompany('purchase_orders.manage_expenses'),validate({params:purchaseOrderIdParams,body:createPurchaseOrderExpenseBody}),controller.createExpense);
router.put('/:id/expenses/:expenseId',authorizeCompany('purchase_orders.manage_expenses'),validate({params:purchaseOrderExpenseParams,body:updatePurchaseOrderExpenseBody}),controller.updateExpense);
router.delete('/:id/expenses/:expenseId',authorizeCompany('purchase_orders.manage_expenses'),validate({params:purchaseOrderExpenseParams,body:deletePurchaseOrderExpenseBody}),controller.deleteExpense);
router.post('/:id/expenses/:expenseId/documents/upload',authorizeCompany('purchase_orders.manage_documents'),validate({params:purchaseOrderExpenseParams,body:preparePurchaseOrderDocumentBody}),controller.prepareDocument);
router.post('/:id/expenses/:expenseId/documents',authorizeCompany('purchase_orders.manage_documents'),validate({params:purchaseOrderExpenseParams,body:registerPurchaseOrderDocumentBody}),controller.registerDocument);
router.get('/:id/expenses/:expenseId/documents/:documentId',authorizeCompany('purchase_orders.read'),validate({params:purchaseOrderDocumentParams}),controller.readDocument);
router.delete('/:id/expenses/:expenseId/documents/:documentId',authorizeCompany('purchase_orders.manage_documents'),validate({params:purchaseOrderDocumentParams}),controller.deleteDocument);
return router;}
