import { Prisma } from '@prisma/client';
import { AppError } from '../../core/errors/app-error.js';
import { concurrencyConflict } from '../../core/errors/concurrency.js';
import { errorCodes } from '../../core/errors/error-codes.js';
import { paginationMeta } from '../../core/validation/pagination.js';
import { businessCodeEntities, generateBusinessCode } from '../../core/code-generation/business-code.js';
import { entityChangeOperations, entitySchemas, entityTypes } from '../entity-changes/entity-change.constants.js';
import { purchaseOrderSnapshot } from '../entity-changes/entity-change.snapshots.js';
const d=(v)=>new Prisma.Decimal(v), round=(v)=>v.toDecimalPlaces(6,Prisma.Decimal.ROUND_HALF_UP);
const invalid=(message,statusCode=400)=>new AppError({code:errorCodes.validation,message,statusCode});
const missing=()=>new AppError({code:errorCodes.notFound,message:'The requested purchase order was not found.',statusCode:404});
export function createPurchaseOrdersService({repository,storage,entityChangeService,runInTransaction,generateCode=generateBusinessCode}){
  const get=async(companyId,id,client)=>{const value=await repository.find(companyId,id,client);if(!value)throw missing();return value;};
  const record=(companyId,oldValue,newValue,context,operation,metadata,client)=>entityChangeService?.record({schemaName:entitySchemas.companies,entityType:entityTypes.purchaseOrder,entityId:newValue?.id??oldValue.id,companyId,operation,context,oldValues:purchaseOrderSnapshot(oldValue),newValues:purchaseOrderSnapshot(newValue),metadata},client);
  const editable=(order)=>{if(!['DRAFT','PENDING_APPROVAL'].includes(order.status))throw invalid('Expenses can only be changed before the order is approved.',409);};
  const transition=async(companyId,id,body,context,rule)=>{const old=await get(companyId,id);if(!rule.from.includes(old.status))throw invalid(`An order in status ${old.status} cannot be ${rule.verb}.`,409);return runInTransaction(async(client)=>{const updated=await repository.transition(companyId,id,new Date(body.expectedUpdatedAt),rule.from,rule.data(body,context.actorUserId),client);if(!updated)throw concurrencyConflict('purchase order',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:rule.reason},client);return updated;});};
  return {
    async list(companyId,query){const result=await repository.list(companyId,query);return{purchaseOrders:result.items,pagination:paginationMeta({...query,total:result.total})};},
    get,
    async generate(companyId,data,context){if(new Date(data.expectedDate)<new Date(data.orderDate))throw invalid('Expected date cannot be earlier than order date.');return runInTransaction(async(client)=>{const request=await repository.findAwards(companyId,data.purchaseRequestId,client);if(!request)throw invalid('The purchase request is not available for order generation.',409);if(request.branch.status!=='ACTIVE'||!request.warehouse.isActive)throw invalid('The destination branch and warehouse must be active.');const sources=request.quotationLinks.filter((x)=>x.details.length);if(!sources.length)throw invalid('There are no unprocessed awarded quantities for this request.',409);const created=[];for(const source of sources){const q=source.purchaseQuotation;if(q.status!=='SELECTED')throw invalid('Every source quotation must be selected.',409);let subtotal=d(0),discount=d(0),tax=d(0);const details=source.details.map((link,index)=>{const item=link.quotationDetail,quantity=d(link.awardedQuantity),gross=round(quantity.mul(item.unitPrice)),discountAmount=round(gross.mul(item.discountRate).div(100)),net=round(gross.sub(discountAmount)),taxAmount=round(net.mul(item.taxRate).div(100));subtotal=subtotal.add(gross);discount=discount.add(discountAmount);tax=tax.add(taxAmount);return{companyId,purchaseQuotationRequestDetailId:link.id,lineNumber:index+1,productId:item.productId,productUnitId:item.productUnitId,quantity,unitPrice:item.unitPrice,grossAmount:gross,discountRate:item.discountRate,discountAmount,subtotal:net,taxRate:item.taxRate,taxAmount,total:round(net.add(taxAmount)),notes:item.notes};});const merchandise=round(subtotal.sub(discount).add(tax));const ratio=d(q.subtotal).greaterThan(0)?round(subtotal.sub(discount).div(q.subtotal)):d(0);const expenses=q.expenses.map((expense,index)=>({companyId,expenseTypeId:expense.expenseTypeId,lineNumber:index+1,description:expense.description,amount:round(d(expense.amount).mul(ratio)),isCostable:true})).filter((x)=>x.amount.greaterThan(0));const additional=round(expenses.reduce((sum,x)=>sum.add(x.amount),d(0)));const order=await repository.create({companyId,code:await generateCode(client,businessCodeEntities.purchaseOrder,{companyId}),supplierId:q.supplierId,supplierContactId:q.supplierContactId,branchId:request.branchId,warehouseId:request.warehouseId,purchaseQuotationId:q.id,createdByUserId:context.actorUserId,orderDate:new Date(data.orderDate),expectedDate:new Date(data.expectedDate),currencyCode:q.currencyCode,exchangeRate:q.exchangeRate,exchangeRateDate:q.exchangeRateDate,paymentTerms:q.paymentTerms,subtotal:round(subtotal),discount:round(discount),tax:round(tax),additionalExpenses:additional,total:round(merchandise.add(additional)),notes:data.notes||null,details:{create:details},expenses:{create:expenses}},client);await record(companyId,null,order,context,entityChangeOperations.create,{purchaseRequestId:data.purchaseRequestId},client);created.push(order);}return created;});},
    submit:(c,i,b,x)=>transition(c,i,b,x,{from:['DRAFT'],verb:'submitted',reason:'SUBMIT',data:()=>({status:'PENDING_APPROVAL',submittedAt:new Date()})}),
    approve:(c,i,b,x)=>transition(c,i,b,x,{from:['PENDING_APPROVAL'],verb:'approved',reason:'APPROVE',data:(_v,u)=>({status:'APPROVED',approvedAt:new Date(),approvedByUserId:u})}),
    send:(c,i,b,x)=>transition(c,i,b,x,{from:['APPROVED'],verb:'sent',reason:'SEND',data:(_v,u)=>({status:'SENT',sentAt:new Date(),sentByUserId:u})}),
    cancel:(c,i,b,x)=>transition(c,i,b,x,{from:['DRAFT','PENDING_APPROVAL','APPROVED','SENT'],verb:'cancelled',reason:'CANCEL',data:(v,u)=>({status:'CANCELLED',cancelledAt:new Date(),cancelledByUserId:u,cancellationReason:v.reason})}),
    async createExpense(companyId,id,data,context){const old=await get(companyId,id);editable(old);return runInTransaction(async(client)=>{if(!await repository.findExpenseType(companyId,data.expenseTypeId,client))throw invalid('The expense type is not active or does not belong to this company.');const next=await repository.nextExpenseLine(companyId,id,client);await repository.createExpense({companyId,purchaseOrderId:id,expenseTypeId:data.expenseTypeId,lineNumber:(next._max.lineNumber??0)+1,description:data.description??null,amount:d(data.amount),isCostable:data.isCostable},client);const updated=await repository.recalculate(companyId,id,new Date(data.expectedOrderUpdatedAt),client);if(!updated)throw concurrencyConflict('purchase order',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'CREATE_EXPENSE'},client);return updated;});},
    async updateExpense(companyId,id,expenseId,data,context){const old=await get(companyId,id);editable(old);const expense=await repository.findExpense(companyId,id,expenseId);if(!expense)throw invalid('The requested order expense was not found.',404);return runInTransaction(async(client)=>{if(!await repository.findExpenseType(companyId,data.expenseTypeId,client))throw invalid('The expense type is not active or does not belong to this company.');const changed=await repository.updateExpense(companyId,id,expenseId,new Date(data.expectedUpdatedAt),{expenseTypeId:data.expenseTypeId,description:data.description??null,amount:d(data.amount),isCostable:data.isCostable},client);if(!changed)throw concurrencyConflict('purchase order expense',expense.updatedAt);const updated=await repository.recalculate(companyId,id,new Date(data.expectedOrderUpdatedAt),client);if(!updated)throw concurrencyConflict('purchase order',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'UPDATE_EXPENSE',expenseId},client);return updated;});},
    async deleteExpense(companyId,id,expenseId,data,context){const old=await get(companyId,id);editable(old);const expense=await repository.findExpense(companyId,id,expenseId);if(!expense)throw invalid('The requested order expense was not found.',404);if(expense.documents.length)throw invalid('Remove the expense documents before deleting the expense.',409);return runInTransaction(async(client)=>{if(!await repository.deleteExpense(companyId,id,expenseId,new Date(data.expectedUpdatedAt),client))throw concurrencyConflict('purchase order expense',expense.updatedAt);const updated=await repository.recalculate(companyId,id,new Date(data.expectedOrderUpdatedAt),client);if(!updated)throw concurrencyConflict('purchase order',old.updatedAt);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'DELETE_EXPENSE',expenseId},client);return updated;});},
    async prepareDocument(companyId,id,expenseId,data){await get(companyId,id);if(!await repository.findExpense(companyId,id,expenseId))throw invalid('The requested order expense was not found.',404);return storage.preparePurchaseOrderDocumentUpload({companyId,purchaseOrderId:id,expenseId,contentType:data.contentType,sizeBytes:data.sizeBytes});},
    async registerDocument(companyId,id,expenseId,data,context){const old=await get(companyId,id);if(['CANCELLED','CLOSED'].includes(old.status))throw invalid('Documents cannot be attached to a closed or cancelled order.',409);if(!await repository.findExpense(companyId,id,expenseId))throw invalid('The requested order expense was not found.',404);const metadata=await storage.verifyPurchaseOrderDocumentUpload({companyId,purchaseOrderId:id,expenseId,storageKey:data.storageKey});return runInTransaction(async(client)=>{const document=await repository.createDocument({companyId,purchaseOrderExpenseId:expenseId,storageKey:data.storageKey,originalFileName:data.originalFileName,contentType:metadata.contentType,sizeBytes:metadata.sizeBytes,uploadedByUserId:context.actorUserId},client);const updated=await get(companyId,id,client);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'ATTACH_EXPENSE_DOCUMENT',expenseId,documentId:document.id},client);return document;});},
    async readDocument(companyId,id,expenseId,documentId){const document=await repository.findDocument(companyId,id,expenseId,documentId);if(!document)throw invalid('The requested expense document was not found.',404);return {...document,...await storage.createReadUrl({companyId,storageKey:document.storageKey,forceSigned:true})};},
    async deleteDocument(companyId,id,expenseId,documentId,_data,context){const old=await get(companyId,id);editable(old);const document=await repository.findDocument(companyId,id,expenseId,documentId);if(!document)throw invalid('The requested expense document was not found.',404);await runInTransaction(async(client)=>{await repository.deleteDocument(companyId,id,expenseId,documentId,client);const updated=await get(companyId,id,client);await record(companyId,old,updated,context,entityChangeOperations.update,{reason:'DELETE_EXPENSE_DOCUMENT',expenseId,documentId},client);});await storage.deleteObject({companyId,storageKey:document.storageKey}).catch(()=>undefined);},
  };
}
