import { Prisma } from '@prisma/client';
import { AppError } from '../../core/errors/app-error.js';
import { concurrencyConflict } from '../../core/errors/concurrency.js';
import { errorCodes } from '../../core/errors/error-codes.js';
import { paginationMeta } from '../../core/validation/pagination.js';
import { businessCodeEntities, generateBusinessCode } from '../../core/code-generation/business-code.js';
const d=(v)=>new Prisma.Decimal(v), round=(v)=>v.toDecimalPlaces(6,Prisma.Decimal.ROUND_HALF_UP);
const invalid=(message,statusCode=400)=>new AppError({code:errorCodes.validation,message,statusCode});
const missing=()=>new AppError({code:errorCodes.notFound,message:'The requested purchase order was not found.',statusCode:404});
export function createPurchaseOrdersService({repository,runInTransaction,generateCode=generateBusinessCode}){
  const get=async(companyId,id,client)=>{const value=await repository.find(companyId,id,client);if(!value)throw missing();return value;};
  const transition=async(companyId,id,body,context,rule)=>{const old=await get(companyId,id);if(!rule.from.includes(old.status))throw invalid(`An order in status ${old.status} cannot be ${rule.verb}.`,409);return runInTransaction(async(client)=>{const updated=await repository.transition(companyId,id,new Date(body.expectedUpdatedAt),rule.from,rule.data(body,context.actorUserId),client);if(!updated)throw concurrencyConflict('purchase order',old.updatedAt);return updated;});};
  return {
    async list(companyId,query){const result=await repository.list(companyId,query);return{purchaseOrders:result.items,pagination:paginationMeta({...query,total:result.total})};},
    get,
    async generate(companyId,data,context){if(new Date(data.expectedDate)<new Date(data.orderDate))throw invalid('Expected date cannot be earlier than order date.');return runInTransaction(async(client)=>{const request=await repository.findAwards(companyId,data.purchaseRequestId,client);if(!request)throw invalid('The purchase request is not available for order generation.',409);if(request.branch.status!=='ACTIVE'||!request.warehouse.isActive)throw invalid('The destination branch and warehouse must be active.');const sources=request.quotationLinks.filter((x)=>x.details.length);if(!sources.length)throw invalid('There are no unprocessed awarded quantities for this request.',409);const created=[];for(const source of sources){const q=source.purchaseQuotation;if(q.status!=='SELECTED')throw invalid('Every source quotation must be selected.',409);let subtotal=d(0),discount=d(0),tax=d(0);const details=source.details.map((link,index)=>{const item=link.quotationDetail,quantity=d(link.awardedQuantity),gross=round(quantity.mul(item.unitPrice)),discountAmount=round(gross.mul(item.discountRate).div(100)),net=round(gross.sub(discountAmount)),taxAmount=round(net.mul(item.taxRate).div(100));subtotal=subtotal.add(gross);discount=discount.add(discountAmount);tax=tax.add(taxAmount);return{companyId,purchaseQuotationRequestDetailId:link.id,lineNumber:index+1,productId:item.productId,productUnitId:item.productUnitId,quantity,unitPrice:item.unitPrice,grossAmount:gross,discountRate:item.discountRate,discountAmount,subtotal:net,taxRate:item.taxRate,taxAmount,total:round(net.add(taxAmount)),notes:item.notes};});const merchandise=round(subtotal.sub(discount).add(tax));const ratio=d(q.subtotal).greaterThan(0)?round(subtotal.sub(discount).div(q.subtotal)):d(0);const expenses=q.expenses.map((expense,index)=>({companyId,expenseTypeId:expense.expenseTypeId,lineNumber:index+1,description:expense.description,amount:round(d(expense.amount).mul(ratio)),isCostable:true})).filter((x)=>x.amount.greaterThan(0));const additional=round(expenses.reduce((sum,x)=>sum.add(x.amount),d(0)));created.push(await repository.create({companyId,code:await generateCode(client,businessCodeEntities.purchaseOrder,{companyId}),supplierId:q.supplierId,supplierContactId:q.supplierContactId,branchId:request.branchId,warehouseId:request.warehouseId,purchaseQuotationId:q.id,createdByUserId:context.actorUserId,orderDate:new Date(data.orderDate),expectedDate:new Date(data.expectedDate),currencyCode:q.currencyCode,exchangeRate:q.exchangeRate,exchangeRateDate:q.exchangeRateDate,paymentTerms:q.paymentTerms,subtotal:round(subtotal),discount:round(discount),tax:round(tax),additionalExpenses:additional,total:round(merchandise.add(additional)),notes:data.notes||null,details:{create:details},expenses:{create:expenses}},client));}return created;});},
    submit:(c,i,b,x)=>transition(c,i,b,x,{from:['DRAFT'],verb:'submitted',data:()=>({status:'PENDING_APPROVAL',submittedAt:new Date()})}),
    approve:(c,i,b,x)=>transition(c,i,b,x,{from:['PENDING_APPROVAL'],verb:'approved',data:(_v,u)=>({status:'APPROVED',approvedAt:new Date(),approvedByUserId:u})}),
    send:(c,i,b,x)=>transition(c,i,b,x,{from:['APPROVED'],verb:'sent',data:(_v,u)=>({status:'SENT',sentAt:new Date(),sentByUserId:u})}),
    cancel:(c,i,b,x)=>transition(c,i,b,x,{from:['DRAFT','PENDING_APPROVAL','APPROVED','SENT'],verb:'cancelled',data:(v,u)=>({status:'CANCELLED',cancelledAt:new Date(),cancelledByUserId:u,cancellationReason:v.reason})}),
  };
}
