CREATE TABLE `purchase_orders` (
 `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, `uuid` CHAR(36) NOT NULL, `company_id` INTEGER UNSIGNED NOT NULL, `code` VARCHAR(50) NOT NULL,
 `supplier_id` INTEGER UNSIGNED NOT NULL, `supplier_contact_id` INTEGER UNSIGNED NULL, `branch_id` INTEGER UNSIGNED NOT NULL, `warehouse_id` INTEGER UNSIGNED NOT NULL, `purchase_quotation_id` INTEGER UNSIGNED NULL, `created_by_user_id` INTEGER UNSIGNED NOT NULL,
 `order_date` DATETIME(3) NOT NULL, `expected_date` DATETIME(3) NOT NULL, `currency_code` CHAR(3) NOT NULL, `exchange_rate` DECIMAL(18,8) NOT NULL DEFAULT 1, `exchange_rate_date` DATE NULL, `payment_terms` VARCHAR(500) NULL,
 `subtotal` DECIMAL(18,6) NOT NULL DEFAULT 0, `discount` DECIMAL(18,6) NOT NULL DEFAULT 0, `tax` DECIMAL(18,6) NOT NULL DEFAULT 0, `additional_expenses` DECIMAL(18,6) NOT NULL DEFAULT 0, `total` DECIMAL(18,6) NOT NULL DEFAULT 0,
 `status` ENUM('DRAFT','PENDING_APPROVAL','APPROVED','SENT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED','CLOSED') NOT NULL DEFAULT 'DRAFT', `notes` TEXT NULL,
 `submitted_at` DATETIME(3) NULL, `approved_at` DATETIME(3) NULL, `approved_by_user_id` INTEGER UNSIGNED NULL, `sent_at` DATETIME(3) NULL, `sent_by_user_id` INTEGER UNSIGNED NULL, `cancelled_at` DATETIME(3) NULL, `cancelled_by_user_id` INTEGER UNSIGNED NULL, `cancellation_reason` TEXT NULL,
 `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL,
 UNIQUE INDEX `purchase_orders_uuid_key` (`uuid`), UNIQUE INDEX `purchase_orders_company_code_key` (`company_id`,`code`), UNIQUE INDEX `purchase_orders_id_company_key` (`id`,`company_id`),
 INDEX `purchase_orders_company_status_date_idx` (`company_id`,`status`,`order_date`), INDEX `purchase_orders_supplier_idx` (`company_id`,`supplier_id`), INDEX `purchase_orders_destination_idx` (`company_id`,`branch_id`,`warehouse_id`), INDEX `purchase_orders_quotation_idx` (`company_id`,`purchase_quotation_id`), INDEX `purchase_orders_created_by_idx` (`created_by_user_id`), INDEX `purchase_orders_approved_by_idx` (`approved_by_user_id`), INDEX `purchase_orders_sent_by_idx` (`sent_by_user_id`), INDEX `purchase_orders_cancelled_by_idx` (`cancelled_by_user_id`),
 CONSTRAINT `purchase_orders_dates_check` CHECK (`expected_date` >= `order_date`), CONSTRAINT `purchase_orders_totals_check` CHECK (`subtotal` >= 0 AND `discount` >= 0 AND `tax` >= 0 AND `additional_expenses` >= 0 AND `total` >= 0), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_details` (
 `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, `company_id` INTEGER UNSIGNED NOT NULL, `purchase_order_id` INTEGER UNSIGNED NOT NULL, `purchase_quotation_request_detail_id` INTEGER UNSIGNED NULL, `line_number` SMALLINT UNSIGNED NOT NULL, `product_id` INTEGER UNSIGNED NOT NULL, `product_unit_id` INTEGER UNSIGNED NOT NULL,
 `quantity` DECIMAL(18,4) NOT NULL, `unit_price` DECIMAL(18,6) NOT NULL, `gross_amount` DECIMAL(18,6) NOT NULL, `discount_rate` DECIMAL(9,6) NOT NULL DEFAULT 0, `discount_amount` DECIMAL(18,6) NOT NULL DEFAULT 0, `subtotal` DECIMAL(18,6) NOT NULL, `tax_rate` DECIMAL(9,6) NOT NULL DEFAULT 0, `tax_amount` DECIMAL(18,6) NOT NULL DEFAULT 0, `total` DECIMAL(18,6) NOT NULL, `notes` TEXT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL,
 UNIQUE INDEX `purchase_order_details_award_key` (`purchase_quotation_request_detail_id`,`company_id`), UNIQUE INDEX `purchase_order_details_line_key` (`company_id`,`purchase_order_id`,`line_number`), UNIQUE INDEX `purchase_order_details_id_company_key` (`id`,`company_id`), INDEX `purchase_order_details_product_idx` (`company_id`,`product_id`), CONSTRAINT `purchase_order_details_values_check` CHECK (`quantity` > 0 AND `unit_price` >= 0 AND `gross_amount` >= 0 AND `discount_rate` BETWEEN 0 AND 100 AND `discount_amount` >= 0 AND `subtotal` >= 0 AND `tax_rate` BETWEEN 0 AND 100 AND `tax_amount` >= 0 AND `total` >= 0), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_expenses` (
 `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, `company_id` INTEGER UNSIGNED NOT NULL, `purchase_order_id` INTEGER UNSIGNED NOT NULL, `expense_type_id` INTEGER UNSIGNED NOT NULL, `line_number` SMALLINT UNSIGNED NOT NULL, `description` VARCHAR(500) NULL, `amount` DECIMAL(18,6) NOT NULL, `is_costable` BOOLEAN NOT NULL DEFAULT true, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL,
 UNIQUE INDEX `purchase_order_expenses_line_key` (`company_id`,`purchase_order_id`,`line_number`), UNIQUE INDEX `purchase_order_expenses_id_company_key` (`id`,`company_id`), INDEX `purchase_order_expenses_type_idx` (`company_id`,`expense_type_id`), CONSTRAINT `purchase_order_expenses_amount_check` CHECK (`amount` > 0), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_expense_documents` (
 `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, `company_id` INTEGER UNSIGNED NOT NULL, `purchase_order_expense_id` INTEGER UNSIGNED NOT NULL, `storage_key` VARCHAR(500) NOT NULL, `original_file_name` VARCHAR(255) NOT NULL, `content_type` VARCHAR(100) NOT NULL, `size_bytes` INTEGER UNSIGNED NOT NULL, `uploaded_by_user_id` INTEGER UNSIGNED NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL,
 UNIQUE INDEX `purchase_order_expense_documents_storage_key` (`storage_key`), UNIQUE INDEX `purchase_order_expense_documents_id_company_key` (`id`,`company_id`), INDEX `purchase_order_expense_documents_expense_idx` (`company_id`,`purchase_order_expense_id`), INDEX `purchase_order_expense_documents_uploaded_by_idx` (`uploaded_by_user_id`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `purchase_orders` ADD CONSTRAINT `purchase_orders_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_supplier_company_fkey` FOREIGN KEY (`supplier_id`,`company_id`) REFERENCES `suppliers` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_contact_company_fkey` FOREIGN KEY (`supplier_contact_id`,`company_id`) REFERENCES `supplier_contacts` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_branch_company_fkey` FOREIGN KEY (`branch_id`,`company_id`) REFERENCES `branches` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_warehouse_company_fkey` FOREIGN KEY (`warehouse_id`,`company_id`) REFERENCES `warehouses` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_quotation_company_fkey` FOREIGN KEY (`purchase_quotation_id`,`company_id`) REFERENCES `purchase_quotations` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_created_by_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_approved_by_fkey` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_sent_by_fkey` FOREIGN KEY (`sent_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_orders_cancelled_by_fkey` FOREIGN KEY (`cancelled_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `purchase_order_details` ADD CONSTRAINT `purchase_order_details_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_details_order_company_fkey` FOREIGN KEY (`purchase_order_id`,`company_id`) REFERENCES `purchase_orders` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_details_award_company_fkey` FOREIGN KEY (`purchase_quotation_request_detail_id`,`company_id`) REFERENCES `purchase_quotation_request_details` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_details_product_company_fkey` FOREIGN KEY (`product_id`,`company_id`) REFERENCES `products` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_details_unit_company_fkey` FOREIGN KEY (`product_unit_id`,`company_id`) REFERENCES `product_units` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `purchase_order_expenses` ADD CONSTRAINT `purchase_order_expenses_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_expenses_order_company_fkey` FOREIGN KEY (`purchase_order_id`,`company_id`) REFERENCES `purchase_orders` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_expenses_type_company_fkey` FOREIGN KEY (`expense_type_id`,`company_id`) REFERENCES `expense_types` (`id`,`company_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `purchase_order_expense_documents` ADD CONSTRAINT `purchase_order_expense_documents_company_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_expense_documents_expense_company_fkey` FOREIGN KEY (`purchase_order_expense_id`,`company_id`) REFERENCES `purchase_order_expenses` (`id`,`company_id`) ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT `purchase_order_expense_documents_uploaded_by_fkey` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO `permissions` (`code`,`resource`,`action`,`description`,`scope`,`created_at`) VALUES
('purchase_orders.read','purchase_orders','read','View purchase orders.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.create','purchase_orders','create','Generate purchase orders.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.submit','purchase_orders','submit','Submit purchase orders for approval.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.approve','purchase_orders','approve','Approve purchase orders.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.send','purchase_orders','send','Mark purchase orders as sent.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.cancel','purchase_orders','cancel','Cancel purchase orders.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.manage_expenses','purchase_orders','manage_expenses','Manage purchase order expenses.','COMPANY',CURRENT_TIMESTAMP(3)),('purchase_orders.manage_documents','purchase_orders','manage_documents','Manage purchase order expense documents.','COMPANY',CURRENT_TIMESTAMP(3));
INSERT IGNORE INTO `company_role_permissions` (`role_id`,`permission_id`) SELECT cr.`id`,p.`id` FROM `company_roles` cr JOIN `permissions` p WHERE (cr.`code` IN ('OWNER','ADMIN') AND p.`code` LIKE 'purchase_orders.%') OR (cr.`code`='OPERATOR' AND p.`code` IN ('purchase_orders.read','purchase_orders.create','purchase_orders.submit','purchase_orders.send')) OR (cr.`code`='READ_ONLY' AND p.`code`='purchase_orders.read');
